version: '4'

services:
  postgres:
    image: postgis/postgis:16-master
    restart: always
    ports:
      - 5432:5432
    env_file: ./.env
    volumes:
      - ./docker/pg-scripts:/docker-entrypoint-initdb.d
      - db:/var/lib/postgres
    environment:
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - POSTGRES_MULTIPLE_DATABASES=hiking,users,projects,task

  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    ports:
      - '6379:6379'

volumes: 
  db:

networks:
  internal:
    name: internal
    driver: bridge